name: Prepare

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      shell: sh
