name: Prepare

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4

    - name: Store cache path
      run: echo "cache_path=$(npm config get cache)" >> $GITHUB_ENV
      shell: sh

    - name: Restore cache
      uses: actions/cache@v4
      with:
        path: ${{ env.cache_path }}
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm ci
      shell: sh
