name: Build and pages deploy

on:
  workflow_run:
    workflows:
      - Lint and test
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages-deploy'
  cancel-in-progress: true

jobs:
  build-and-pages-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build and pages deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Build
        run: npm run build
        env:
          PUBLIC_BASE_PATH: /${{ github.event.repository.name }}/

      - name: Setup pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

      - name: Upload artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: './build/client/'

      - name: Pages deploy
        id: deploy
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
