name: Build and cloudflare pages deploy

on:
  workflow_run:
    workflows:
      - Lint and test
    types:
      - completed

permissions:
  contents: read

concurrency:
  group: 'cloudflare-pages-deploy'
  cancel-in-progress: true

jobs:
  build-and-cloudflare-pages-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build and cloudflare pages deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Build
        run: npm run build

      - name: Cloudflare pages deploy
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
          directory: ./build/client
          wranglerVersion: '3'
